#!/usr/bin/env php
<?php

$appFile = __DIR__ . '/src/app.php';
$consoleFile = __DIR__ . '/src/console.php';

if (!file_exists($appFile)) {
    die("Archivo $appFile no existe.");
} elseif (!file_exists($consoleFile)) {
    die("Archivo $consoleFile no existe.");
} else {
    require $appFile;
    $console = require $consoleFile;
    $console->run();
}